// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VictorySearcher.Service.Infrastructure.Persistence;

#nullable disable

namespace VictorySearcher.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.ScoringRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId");

                    b.ToTable("ScoringRequests");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.ScoringResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceScore")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUncertain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_uncertain");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkillsScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("ResumeId");

                    b.ToTable("ScoringResults");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ExtraRequirements")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Trend")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Resume", b =>
                {
                    b.HasOne("VictorySearcher.Service.Domain.Entities.Vacancy", "Vacancy")
                        .WithMany("Resumes")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.ScoringRequest", b =>
                {
                    b.HasOne("VictorySearcher.Service.Domain.Entities.Vacancy", "Vacancy")
                        .WithMany("ScoringRequests")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.ScoringResult", b =>
                {
                    b.HasOne("VictorySearcher.Service.Domain.Entities.ScoringRequest", "Request")
                        .WithMany("Results")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VictorySearcher.Service.Domain.Entities.Resume", "Resume")
                        .WithMany("ScoringResults")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("VictorySearcher.Service.Domain.Entities.RequirementCoverage", "RequirementsAnalysis", b1 =>
                        {
                            b1.Property<Guid>("ScoringResultId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("Covered")
                                .HasColumnType("boolean");

                            b1.Property<string>("Evidence")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Requirement")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ScoringResultId", "__synthesizedOrdinal");

                            b1.ToTable("ScoringResults");

                            b1.ToJson("requirements_analysis");

                            b1.WithOwner()
                                .HasForeignKey("ScoringResultId");
                        });

                    b.Navigation("Request");

                    b.Navigation("RequirementsAnalysis");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Vacancy", b =>
                {
                    b.HasOne("VictorySearcher.Service.Domain.Entities.User", "CreatedBy")
                        .WithMany("Vacancies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Resume", b =>
                {
                    b.Navigation("ScoringResults");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.ScoringRequest", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.User", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("VictorySearcher.Service.Domain.Entities.Vacancy", b =>
                {
                    b.Navigation("Resumes");

                    b.Navigation("ScoringRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
